/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-17 05:30:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Web Fonts -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Icon Font Stylesheet -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Libraries Stylesheet -->\r\n");
      out.write("<link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"lib/owlcarousel/assets/owl.carousel.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Stylesheet -->\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("h2 {\r\n");
      out.write("	font-family: Sans-serif;\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: Blue;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	font-family: verdana;\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	background: #00B074 !important;;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	/*border: 4px solid #000000;\r\n");
      out.write(" border-style: dashed;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.inner {\r\n");
      out.write("	border: 10px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text], input[type=email], input[type=number] {\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	padding: 6px 12px;\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit], input[type=reset] {\r\n");
      out.write("	width: 15%;\r\n");
      out.write("	padding: 8px 12px;\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Carousel Start -->\r\n");
      out.write("		<div class=\"container-fluid p-0\">\r\n");
      out.write("			<div class=\"owl-carousel header-carousel position-relative\">\r\n");
      out.write("				<div class=\"owl-carousel-item position-relative\">\r\n");
      out.write("					<img class=\"img-fluid\" src=\"img/carousel-1.jpg\" alt=\"\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center\"\r\n");
      out.write("						style=\"background: rgba(43, 57, 64, .5);\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<div class=\"row justify-content-start\">\r\n");
      out.write("								<div class=\"col-10 col-lg-8\">\r\n");
      out.write("									<h1 class=\"display-3 text-white animated slideInDown mb-4\">Find\r\n");
      out.write("										The Perfect Job That You Deserved</h1>\r\n");
      out.write("									<p class=\"fs-5 fw-medium text-white mb-4 pb-2\">Vero elitr\r\n");
      out.write("										justo clita lorem. Ipsum dolor at sed stet sit diam no. Kasd\r\n");
      out.write("										rebum ipsum et diam justo clita et kasd rebum sea elitr.</p>\r\n");
      out.write("									<a href=\"\"\r\n");
      out.write("										class=\"btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft\">Search\r\n");
      out.write("										A Job</a> <a href=\"\"\r\n");
      out.write("										class=\"btn btn-secondary py-md-3 px-md-5 animated slideInRight\">Find\r\n");
      out.write("										A Talent</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"owl-carousel-item position-relative\">\r\n");
      out.write("					<img class=\"img-fluid\" src=\"img/carousel-2.jpg\" alt=\"\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center\"\r\n");
      out.write("						style=\"background: rgba(43, 57, 64, .5);\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<div class=\"row justify-content-start\">\r\n");
      out.write("								<div class=\"col-10 col-lg-8\">\r\n");
      out.write("									<h1 class=\"display-3 text-white animated slideInDown mb-4\">Find\r\n");
      out.write("										The Best Startup Job That Fit You</h1>\r\n");
      out.write("									<p class=\"fs-5 fw-medium text-white mb-4 pb-2\">Vero elitr\r\n");
      out.write("										justo clita lorem. Ipsum dolor at sed stet sit diam no. Kasd\r\n");
      out.write("										rebum ipsum et diam justo clita et kasd rebum sea elitr.</p>\r\n");
      out.write("									<a href=\"\"\r\n");
      out.write("										class=\"btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft\">Search\r\n");
      out.write("										A Job</a> <a href=\"\"\r\n");
      out.write("										class=\"btn btn-secondary py-md-3 px-md-5 animated slideInRight\">Find\r\n");
      out.write("										A Talent</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write(" \r\n");
      out.write("		<!-- Carousel End -->\r\n");
      out.write("		<!-- Registration Start -->\r\n");
      out.write("\r\n");
      out.write("		<div style=\"background-color: #EFFDF5;\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<h1 style=\"text-align:center;\">Register Here !</h1>\r\n");
      out.write("			<br>\r\n");
      out.write("			<form action=\"Demo\" method=\"post\">\r\n");
      out.write("				<table align=\"center\" cellpadding=\"10\">\r\n");
      out.write("					<!--------------------- First Name ------------------------------------------>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>First Name</td>\r\n");
      out.write("						<td><input type=\"text\" name=\"FirstName\" maxlength=\"50\"\r\n");
      out.write("							placeholder=\"FirstName\" /> (Max 50 Char)</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!------------------------ Last Name --------------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>Last Name</td>\r\n");
      out.write("						<td><input type=\"text\" name=\"LastName\" maxlength=\"50\"\r\n");
      out.write("							placeholder=\"LastName\" /> (Max 50 Char)</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!-------------------------- Email ID ------------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>Email ID</td>\r\n");
      out.write("						<td><input type=\"email\" name=\"EmailID\" maxlength=\"100\"\r\n");
      out.write("							placeholder=\"example@gmail.com\" /></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!-------------------------- Mobile Number ------------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>Mobile Number</td>\r\n");
      out.write("						<td><input type=\"text\" name=\"MobileNumber\" maxlength=\"12\"\r\n");
      out.write("							placeholder=\"7842xxxxxx\" /> (10 Digits)</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!---------------------- Gender ------------------------------------->\r\n");
      out.write("\r\n");
      out.write("					<!--------------------------Date Of Birth----------------------------------->\r\n");
      out.write("					<!------------------------- Address ---------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>Address<br /> <br /> <br /></td>\r\n");
      out.write("						<td><textarea name=\"Address\" rows=\"10\" cols=\"50\"></textarea></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!-------------------------- City ------------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>City</td>\r\n");
      out.write("						<td><input type=\"text\" name=\"City\" maxlength=\"50\"\r\n");
      out.write("							placeholder=\"City Name\" /> (Max 50 Char)</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!----- -------------------- Pin Code-------------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>Pin Code</td>\r\n");
      out.write("						<td><input type=\"Number\" name=\"PinCode\" maxlength=\"6\"\r\n");
      out.write("							placeholder=\"Enter Pin\" /> (Max 6 Numbers )</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!---------------------------- State ----------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>State</td>\r\n");
      out.write("						<td><input type=\"text\" name=\"State\" maxlength=\"50\"\r\n");
      out.write("							placeholder=\"State\" /> (Max 50 Char)</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!------------------------------ Country --------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>Country</td>\r\n");
      out.write("						<td><input type=\"text\" name=\"Country\" placeholder=\"Country\" /></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!------------------------- Hobbies -------------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>Hobbies <br /> <br /> <br /></td>\r\n");
      out.write("						<td><input type=\"text\" name=\"Hobby\" maxlength=\"50\"\r\n");
      out.write("							placeholder=\"Hobbies\" /> (Max 50 Char)</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!-----------------------Qualification---------------------------------------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td> Highest Qualification <br /> <br /> <br /></td>\r\n");
      out.write("						<td><br /> <input type=\"text\" name=\"Qualification\"\r\n");
      out.write("							maxlength=\"50\" placeholder=\"Enter Here\" /></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<!---------------------------- Courses ----------------------------------->\r\n");
      out.write("\r\n");
      out.write("					<!----------------------- Submit and Reset ----------------------- -------->\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"2\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("							value=\"Submit\"> ");
      out.write("\r\n");
      out.write("							");
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Registration End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		<!-- Back to Top -->\r\n");
      out.write("		<a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top\"><i\r\n");
      out.write("			class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScript Libraries -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"lib/wow/wow.min.js\"></script>\r\n");
      out.write("	<script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("	<script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Template Javascript -->\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
